provider = "bunny"
remote_path = ""
local_path = "public"
ignore = []
remote_ignore = []

[bunny]
storage_zone = "robbrazier"

[[redirects]]
from = "*://www.robbrazier.com/*"
to = "https://robbrazier.com%{Url.Path}"
